# Global settings
global:
  namespace: bookstore

# Redis settings
redis:
  image: redis:7-alpine
  storageSize: 1Gi
  port: 6379

# Application settings
app:
  image:
    repository: rifatg13/bookstore-app   # твой Docker ID
    tag: latest
    pullPolicy: Always
  port: 8085
  replicas: 1
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: "853496"
    SPRING_REDIS_HOST: redis
    SPRING_REDIS_PORT: "6379"

# Ingress settings
ingress:
  enabled: true
  host: bookstore.local
  ingressClassName: nginx

# ServiceMonitor (for Prometheus)
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 30s

# Включает/выключает установку мониторинга
monitoring:
  enabled: true

# Настройки для kube-prometheus-stack (передаются внутрь зависимого чарта)
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    service:
      type: LoadBalancer
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false