apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: rifatg13/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "853496"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "bookstore-kafka-kafka-bootstrap:9092"
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: bookstore-user
                  key: sasl.jaas.config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"