apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-app
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: SPRING_CONFIG_NAME
              value: "application-k8s"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "853496"
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "bookstore-kafka-kafka-bootstrap:9092"
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: bookstore-user
                  key: sasl.jaas.config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"